# Generated by Django 5.0.3 on 2024-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babyreg_babys_sur_name', models.CharField(max_length=20)),
                ('babyreg_babys_other_names', models.CharField(max_length=20)),
                ('babyreg_babys_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('babyreg_babys_date_of_birth', models.DateField()),
                ('babyreg_parents_sur_name', models.CharField(max_length=20)),
                ('babyreg_parentns_other_names', models.CharField(max_length=20)),
                ('babyreg_parents_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('babyreg_parents_date_of_birth', models.DateField()),
                ('babyreg_parents_telephone', models.IntegerField()),
                ('babyreg_parents_address', models.CharField(max_length=50)),
                ('babyreg_parents_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
