# Generated by Django 5.0.3 on 2024-05-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babiz_sur_name', models.CharField(max_length=20)),
                ('babiz_other_names', models.CharField(max_length=20)),
                ('babiz_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('babiz_date_of_birth', models.DateField()),
                ('parentz_sur_name', models.CharField(max_length=20)),
                ('parentz_other_names', models.CharField(max_length=20)),
                ('parentz_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('parentz_date_of_birth', models.DateField()),
                ('parentz_telephone', models.IntegerField()),
                ('parentz_address', models.CharField(max_length=50)),
                ('parentz_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Baby_Registration',
        ),
    ]
