# Generated by Django 5.0.3 on 2024-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0002_baby_register_delete_baby_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_sur_name', models.CharField(max_length=20)),
                ('sit_other_names', models.CharField(max_length=20)),
                ('sit_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('sit_date_of_birth', models.DateField()),
                ('sit_nin_number', models.IntegerField()),
                ('sit_educlevel', models.CharField(choices=[('Primary', 'Primary'), ('O-Level', 'O-Level'), ('A-Level', 'A-Level'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Others', 'Others')], max_length=20)),
                ('sit_religion', models.CharField(choices=[('Born Aagain', 'Born Aagain'), ('Anglican', 'Anglican'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Others', 'Others')], max_length=20)),
                ('sit_address', models.CharField(choices=[('Kabalagala', 'Kabalagala'), ('Other', 'Other')], max_length=20)),
                ('sit_email', models.EmailField(max_length=50)),
                ('sit_telephone', models.IntegerField()),
                ('snok_sur_name', models.CharField(max_length=20)),
                ('snok_other_names', models.CharField(max_length=10)),
                ('snok_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('snok_date_of_birth', models.DateField()),
                ('snok_address', models.CharField(max_length=50)),
                ('snok_email', models.EmailField(max_length=50)),
                ('snok_telephone', models.IntegerField()),
            ],
        ),
    ]
