# Generated by Django 5.0.3 on 2024-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0003_sitter_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_register',
            name='sit_nin_number',
            field=models.CharField(max_length=20),
        ),
    ]
