# Generated by Django 5.0.3 on 2024-05-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0006_procurement_sales_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_availability', models.CharField(choices=[('On Duty', 'On Duty'), ('Off Duty', 'Off Duty')], max_length=10)),
                ('sitter_time', models.TimeField()),
                ('sitter_date', models.DateField()),
                ('sitter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atsapp.sitter_register')),
            ],
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_sitter_availability',
            field=models.ForeignKey(default='On Duty', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='atsapp.sitter_status'),
        ),
    ]
