# Generated by Django 5.0.3 on 2024-05-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0008_purchase_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='so_item_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atsapp.purchase'),
        ),
        migrations.RemoveField(
            model_name='sales_order',
            name='so_item_number',
        ),
        migrations.RemoveField(
            model_name='sales_order',
            name='so_baby_id',
        ),
        migrations.DeleteModel(
            name='Procurement',
        ),
        migrations.DeleteModel(
            name='Sales_Order',
        ),
    ]
