# Generated by Django 5.0.3 on 2024-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0011_remove_checkin_checkin_sitter_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_sitter_fee_currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=10),
        ),
    ]
