# Generated by Django 5.0.3 on 2024-06-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0012_alter_checkout_checkout_sitter_fee_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='baby_id',
            new_name='checkout_baby_id',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='sitter_id',
            new_name='checkout_sitter_id',
        ),
    ]
