

class Baby_RegistrationForm(forms.Form):
    babyreg_baby_id = forms.AutoField(primary_key=True)
    babyreg_babys_sur_name = forms.CharField(max_length=20)
    babyreg_babys_other_names = forms.CharField(max_length=20)
    babyreg_babys_gender = forms.forms.CharField(max_length=10)
    babyreg_babys_date_of_birth = forms.DateField(auto_now_add=True)
    babyreg_parents_sur_name = forms.CharField(max_length=20)
    babyreg_parentns_other_names = forms.CharField(max_length=20)
    babyreg_parents_gender = forms.CharField(max_length=10)
    babyreg_guardians_telephone = forms.IntegerField(max_length=20)
    babyreg_parents_date_of_birth = forms.DateField(auto_now_add=True)
    babyreg_babys_address = forms.CharField(max_length=200)
    babyreg_parents_sur_name = forms.CharField(max_length=20)
    babyreg_parentns_other_names = forms.CharField(max_length=10)
    babyreg_email = forms.EmailField(max_length=200)

class Sitter_RegistrationForm(forms.Form):
    sitterreg_sitter_id = forms.AutoField(primary_key=True)
    sitterreg_sitter_sur_name = forms.CharField(max_length=20)
    sitterreg_sitter_other_names = forms.CharField(max_length=20)
    sitterreg_sitter_gender = forms.CharField(max_length=20)
    sitterreg_sitter_date_of_birth = forms.DateField(auto_now_add=True)
    sitterreg_sitter_nin_number = forms.IntegerField(max_length=50)
    sitterreg_sitter_educlevel = forms.CharField(max_length=100)
    sitterreg_sitter_religion = forms.CharField(max_length=20)
    sitterreg_nextofkin_address = forms.CharField(max_length=20)
    sitterreg_sitter_email = forms.EmailField(max_length=254)
    sitterreg_sitter_telephone = forms.IntegerField(max_length=20)
    sitterreg_nextofkin_sur_name = forms.CharField(max_length=20)
    sittereg_nextofkin_other_names = forms.CharField(max_length=20)
    sitterreg_nextofkin_gender = forms.CharField(max_length=20)
    sitterreg_nextofkin_date_of_birth = forms.DateField(auto_now_add=True)
    sitterreg_nextofkin_address = forms.CharField(max_length=200)
    sitterreg_nextofkin_email = forms.EmailField(max_length=200)
    sitterreg_nextofkin_telephone = forms.IntegerField(max_length=20)

class CheckinForm(models.Model):
    checkin_baby_id = forms.CharField(max_length=20)
    checkin_time = forms.TimeField(auto_now_add=True)
    checkin_date = forms.DateField(auto_now_add=True)
    checkin_stay_duration = forms.CharField(max_length=20)
    checkin_guardians_sur_name = forms.CharField(max_length=20)
    checkin_guardians_other_names = forms.CharField(max_length=20)
    checkin_guardians_telephone = forms.IntegerField(max_length=20)
    checkin_sitter_id = forms.CharField(max_length=20)
    checkin_babay_fee = forms.CharField(max_length=20)
    checkin_comment = forms.CharField(max_length=1000)

class CheckoutForm(models.Model):
    checkin_baby_id = forms.CharField(max_length=20)
    checkout_time = forms.TimeField(auto_now_add=True)
    checkout_date = forms.DateField(auto_now_add=True)
    checkout_stay_duration = forms.CharField(max_length=20)
    checkout_guardians_sur_name = forms.CharField(max_length=20)
    checkout_guardians_other_names = forms.CharField(max_length=20)
    checkout_guardians_telephone = forms.IntegerField(max_length=20)
    checkout_sitter_id = forms.CharField(max_length=20)
    checkout_sitter_fee = forms.CharField(max_length=20)
    checkout_comment = forms.CharField(max_length=1000)

class Purchase_OrderForm(models.Model):
    po_invoice_number = forms.CharField(max_length=20)
    po_item_number = forms.CharField(max_length=20)
    po_product_name = forms.CharField(max_length=50)
    po_unit_cost = forms.forms.IntegerField()
    po_purchase_date = forms.DateTimeField(auto_now_add=True)
    po_entry_date = forms.DateTimeField(auto_now_add=True)
    po_quantity = forms.IntegerField()
    po_total = forms.IntegerField()

class Sales_OrderForm(models.Model):
    so_baby_id = forms.IntegerField()
    so_date_created = forms.DateTimeField(auto_now_add=True)
    so_product_name = forms.CharField(max_length=20)
    so_unit_price = forms.IntegerField()
    so_quantity = forms.IntegerField()
    so_total = forms.IntegerField()